### ISSUE TITLE
Add a custom dark theme for Github Gist

### ISSUE THREAD

**Issue by yalematta** [yalematta/yalematta.github.io#4]
I have added a custom light theming for the Gists in gist.css, but we still need to add a dark one.
The colors of the gists should change when we change the dark-light mode using the toggle.
Required theme colors exists [here](https://cdn.rawgit.com/lonekorean/gist-syntax-themes/b737b139/stylesheets/solarized-dark.css)

**Comment by krishdevdb** [comment]
I would like to do this @yalematta

**Comment by toth2000** [comment]
Hey @yalematta! Can I work on this issue?.

**Comment by yalematta** [comment]
Sure! Thanks for the taking the time 🙂

**Comment by toth2000** [comment]
Thanks, just one question. Should I change the code of Gist.css like this way?
` body .gist .highlight {
   html[data-theme="light"] {   background: #f1f3f5;  }
  html[data-theme="dark"] {   background: #002b36; }
  }`
I am still learning HTML and CSS, so don't know much.

**Comment by kumarharsh2396** [comment]
Can i work on this issue.

**Comment by mayuribotre15** [comment]
Hey @yalematta! Can I work on this issue? I am pretty sure that I can do your project.

I have recently work on dark-light mode using the toggle. You can check my work at:
https://mayuribotre15.github.io/User-Card-using-Light-and-Dark-mode-Toggle/

Text me for more details.

**Comment by mayuribotre15** [comment]
Thank you for assigning me the project.

I have gone through your work and working on your issue to fix it up.

I will complete the work within 2 days. And get back to you as soon as possible.

**Comment by mayuribotre15** [comment]
I have added the dark mode for your custom theme in gist.css using the toggle.

**Comment by yalematta** [comment]
Thank you @mayuribotre15, great job you did there! I have merged your PR. 
One issue is left which makes the dark theme in the gists not consistent.
If you look at `theme-toggle.html`, you can find an `autoThemeToggle` function that loads the website in a certain theme depending on the user's current time. Currently, when you load the site and it's the time for the dark mode we are getting white gists and when it's the time for the light mode we are getting dark gists. 
When changing the toggle it resets to what it should be. But the problem is when it first loads.

If you have time to look into it I would really appreciate it (Don't forget to pull my changes). 
If not, thanks for what you've done already 🙏

**Comment by Naufal2511** [comment]
I have some experience with CSS, Can I work on the project. If yes, is there anything specific that I should be concentrating on?
